stages:
  - test

always-run:
  stage: test
  script: 
    - echo 'this should always run'
    - echo $CI_EXTERNAL_PULL_REQUEST_IID
    - echo $CI_EXTERNAL_PULL_REQUEST_SOURCE_REPOSITORY
    - echo $CI_EXTERNAL_PULL_REQUEST_TARGET_REPOSITORY
    - echo $CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME
    - echo $CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_SHA
    - echo $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME
    - echo $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_SHA


on-pull-requests:
  stage: test
  script: echo 'this should run on pull requests'
  only:
    - external_pull_requests

except-pull-requests:
  stage: test
  script: echo 'this should not run on pull requests'
  except:
    - external_pull_requests
