apiVersion: v1
kind: Secret
metadata:
    name: defectdojo
    namespace: defectdojo
type: kubernetes.io/opaque
stringData:
    DD_ADMIN_PASSWORD: ENC[AES256_GCM,data:+wwiZASgWnuvmqEzG7RdZXfbjJ8lmtVWW9aqyY0GuW4=,iv:Np710GweMvgbN0Rj4zhhhecIOayRUU9kQciIS6quS64=,tag:3scsgARQUqzAQFBhpq1CGA==,type:str]
    DD_CREDENTIAL_AES_256_KEY: ENC[AES256_GCM,data:ELZrdetDdQLTjo1YOyHVs76FXWP6cebNTSXQfOGupj59njNemXtgzVtkX1qKyyKv33/5Cx/M+5Wc7shjBLk5FLMKN44H+k2xBeWratN64H0n0yJOMYmfWeDsgxrcKwZ2Y2hKMN01Vakut8UR2fTZi9iAJhmO+4djT0jELSU/U04=,iv:Zqm1McT8X8/wBR5AMe0VJJJOZsww3rRkOP5FeJkomJU=,tag:cgidKkj9DBs/73ib270wIA==,type:str]
    DD_SECRET_KEY: ENC[AES256_GCM,data:NFixnnjqSSMEwyjv+KcnrtRLXcw9ojHG66ARTpuep/6AS+6UgibkRWeInP8psJhW0E7QVAVyBkfxUFPc3x8nipO8ecElqxrdYk9LyWuDxYL8dgi+pLC6CUXkKpONlzbAvutDsUqwo+TuqnlsRA4LZCDhvLVsTtJa0OXA/fTIpwk=,iv:Rm7etcuCOpZkEfknsSdO2n8gFYjiX6MPyE1tZLjrwv8=,tag:v0slWOygPtVBrDpEn0dCkQ==,type:str]
    METRICS_HTTP_AUTH_PASSWORD: ENC[AES256_GCM,data:RFXZ1NKgxBsvMpikVWdXocKnpiQEczadPisuMZyNfGc=,iv:X/ctwA1aVwuqx8DRUQIaB8mU1BVpC2v1w8GqUy4RYvk=,tag:0SGUECP5FVoV6ygNFxwRYg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:863306670509:key/a0c98664-e12a-44b1-b3b0-4bb062de7a9e
          created_at: "2022-08-08T19:54:48Z"
          enc: AQICAHjVziYnlSHY7Z0eQ3Zqgn8agwi4T/rSvC3849mciM/AHgFPMZECOWYuSORIzYzkSK1EAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM/7VPOSbFlsNpEdfLAgEQgDuxxv9i/2PbC6LCNpWxiTw5kU1DMrp8SaK6kpBnzQeM+p8LBcX8/TaWORV2XTjxAzOBj86xxcFpcJBCkQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-08T19:54:48Z"
    mac: ENC[AES256_GCM,data:aoMzITAovyH8Y6Es0ZrP/R5l9LlTkCT9gp90HRpGWPpVfV2rKhi1k8qfWbvhSqFMNukbUaZHu5EY4I6u0GcYEfHPSNUINITCP150bS9YeOBh+KHSRPFzv2oZt/TjSw8IYzPEPEKb94+EyKThX/K322v2eBNSDMzgHs9xFGszz4c=,iv:FDjEGhbjDoMIB8VFwPNvtqggHKKjXwFDX5W1kUD08xs=,tag:5Twl5mFr9M0GUd+jwtqGNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: defectdojo-postgresql-specific
    namespace: defectdojo
type: kubernetes.io/opaque
stringData:
    postgresql-password: ENC[AES256_GCM,data:xRPPegFJp0f+lU019PvcLA==,iv:OzWH1xFNI7xpC7QoQy3RA22r9n6em8pH91rYme31Nto=,tag:ahUB95+Vc4irVDkO+cIEVQ==,type:str]
    postgresql-postgres-password: ENC[AES256_GCM,data:Dur/6KTkQZGs+gh6NJwp/Q==,iv:Zc//xTbvQbMcI8OZ3lgpzWIqkoB40pyyYQ8GyuZdflo=,tag:YEWYDQEy+afZbCmEuuizKw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:863306670509:key/a0c98664-e12a-44b1-b3b0-4bb062de7a9e
          created_at: "2022-08-08T19:54:48Z"
          enc: AQICAHjVziYnlSHY7Z0eQ3Zqgn8agwi4T/rSvC3849mciM/AHgFPMZECOWYuSORIzYzkSK1EAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM/7VPOSbFlsNpEdfLAgEQgDuxxv9i/2PbC6LCNpWxiTw5kU1DMrp8SaK6kpBnzQeM+p8LBcX8/TaWORV2XTjxAzOBj86xxcFpcJBCkQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-08T19:54:48Z"
    mac: ENC[AES256_GCM,data:aoMzITAovyH8Y6Es0ZrP/R5l9LlTkCT9gp90HRpGWPpVfV2rKhi1k8qfWbvhSqFMNukbUaZHu5EY4I6u0GcYEfHPSNUINITCP150bS9YeOBh+KHSRPFzv2oZt/TjSw8IYzPEPEKb94+EyKThX/K322v2eBNSDMzgHs9xFGszz4c=,iv:FDjEGhbjDoMIB8VFwPNvtqggHKKjXwFDX5W1kUD08xs=,tag:5Twl5mFr9M0GUd+jwtqGNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: defectdojo-rabbitmq-specific
    namespace: defectdojo
type: kubernetes.io/opaque
stringData:
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:qiuWZDSshxttRpSFoZf/7SuQOrq6cq53kfjFOEtoBTs=,iv:CXC8oD0Lp0hHDlJikQw50rlclKgFiBb/P8GDAOmE54I=,tag:3m7eMQ7hELs7hwrevrJSYw==,type:str]
    rabbitmq-password: ENC[AES256_GCM,data:4fLH7RwBWHZIpg==,iv:7I07H/uZ9p8c8ad0z7rGDD5xUkpdWOV2hQDQt+2TLmU=,tag:8DYdQHUk7GigG27P/zP3ww==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:863306670509:key/a0c98664-e12a-44b1-b3b0-4bb062de7a9e
          created_at: "2022-08-08T19:54:48Z"
          enc: AQICAHjVziYnlSHY7Z0eQ3Zqgn8agwi4T/rSvC3849mciM/AHgFPMZECOWYuSORIzYzkSK1EAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM/7VPOSbFlsNpEdfLAgEQgDuxxv9i/2PbC6LCNpWxiTw5kU1DMrp8SaK6kpBnzQeM+p8LBcX8/TaWORV2XTjxAzOBj86xxcFpcJBCkQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-08T19:54:48Z"
    mac: ENC[AES256_GCM,data:aoMzITAovyH8Y6Es0ZrP/R5l9LlTkCT9gp90HRpGWPpVfV2rKhi1k8qfWbvhSqFMNukbUaZHu5EY4I6u0GcYEfHPSNUINITCP150bS9YeOBh+KHSRPFzv2oZt/TjSw8IYzPEPEKb94+EyKThX/K322v2eBNSDMzgHs9xFGszz4c=,iv:FDjEGhbjDoMIB8VFwPNvtqggHKKjXwFDX5W1kUD08xs=,tag:5Twl5mFr9M0GUd+jwtqGNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: defectdojo-redis-specific
    namespace: defectdojo
type: kubernetes.io/opaque
stringData:
    redis-password: ENC[AES256_GCM,data:i1NFKg4GgRjUoQ==,iv:P4+4Ahh/wo73ffpmQSAJvCa7ctbhk0jzz8kN5/vwCMk=,tag:DH03J7qJaez2uyngdw95tA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:863306670509:key/a0c98664-e12a-44b1-b3b0-4bb062de7a9e
          created_at: "2022-08-08T19:54:48Z"
          enc: AQICAHjVziYnlSHY7Z0eQ3Zqgn8agwi4T/rSvC3849mciM/AHgFPMZECOWYuSORIzYzkSK1EAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM/7VPOSbFlsNpEdfLAgEQgDuxxv9i/2PbC6LCNpWxiTw5kU1DMrp8SaK6kpBnzQeM+p8LBcX8/TaWORV2XTjxAzOBj86xxcFpcJBCkQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-08T19:54:48Z"
    mac: ENC[AES256_GCM,data:aoMzITAovyH8Y6Es0ZrP/R5l9LlTkCT9gp90HRpGWPpVfV2rKhi1k8qfWbvhSqFMNukbUaZHu5EY4I6u0GcYEfHPSNUINITCP150bS9YeOBh+KHSRPFzv2oZt/TjSw8IYzPEPEKb94+EyKThX/K322v2eBNSDMzgHs9xFGszz4c=,iv:FDjEGhbjDoMIB8VFwPNvtqggHKKjXwFDX5W1kUD08xs=,tag:5Twl5mFr9M0GUd+jwtqGNw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
