---
- name: Gather distribution info
  setup:
      gather_subset: distribution,!all,!min
  when:
      - ansible_distribution is not defined
  tags:
      - always

- name: Check ansible version
  fail:
    msg: You must use ansible 2.9 or greater
  when: not ansible_version.full is version_compare('2.9', '>=')
  tags:
  - always

- import_tasks: check_prereqs.yml
  become: no
  when: check_prereqs | bool
  tags: 
    - prereqs

- import_tasks: prelim.yml
  tags: 
    - prelim_tasks
    - always


- include: section_1/main.yml
  when: azfcis_section1 | bool
  tags:
  - section1

- include: section_2/main.yml
  when: azfcis_section2 | bool
  tags:
  - section2


- include: section_3/main.yml
  when: azfcis_section3 | bool
  tags:
  - section3

- include: section_4/main.yml
  when: azfcis_section4 | bool
  tags:
  - section4

- include: section_5/main.yml
  when: azfcis_section5 | bool
  tags:
  - section5

- include: section_6/main.yml
  when: azfcis_section6 | bool
  tags:
  - section6

- include: section_7/main.yml
  when: azfcis_section7 | bool
  tags:
  - section7

- include: section_8/main.yml
  when: azfcis_section8 | bool
  tags:
  - section8

- include: section_9/main.yml
  when: azfcis_section9 | bool
  tags:
  - section9

- name: End
  import_tasks: end.yml