apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Cert-Manager
- kubeflow-manifests/common/cert-manager/cert-manager/base
- kubeflow-manifests/common/cert-manager/kubeflow-issuer/base
# Istio
- kubeflow-manifests/common/istio-1-9/istio-crds/base
- kubeflow-manifests/common/istio-1-9/istio-namespace/base
- kubeflow-manifests/common/istio-1-9/istio-install/base
# OIDC Authservice
- kubeflow-manifests/common/oidc-authservice/base
# Dex
- kubeflow-manifests/common/dex/overlays/istio
# KNative
- kubeflow-manifests/common/knative/knative-serving/overlays/gateways
- kubeflow-manifests/common/knative/knative-eventing/base
- kubeflow-manifests/common/istio-1-9/cluster-local-gateway/base
# Kubeflow namespace
- kubeflow-manifests/common/kubeflow-namespace/base
# Kubeflow Roles
- kubeflow-manifests/common/kubeflow-roles/base
# Kubeflow Istio Resources
- kubeflow-manifests/common/istio-1-9/kubeflow-istio-resources/base
# Kubeflow Pipelines
# - kubeflow-manifests/apps/pipeline/upstream/env/platform-agnostic-multi-user
# Since our container runtime is not docker, using pns executor
- kubeflow-manifests/apps/pipeline/upstream/env/platform-agnostic-multi-user-pns
# KFServing
- kubeflow-manifests/apps/kfserving/upstream/overlays/kubeflow
# Katib
- kubeflow-manifests/apps/katib/upstream/installs/katib-with-kubeflow
# Central Dashboard
- kubeflow-manifests/apps/centraldashboard/upstream/overlays/istio
# Admission Webhook
- kubeflow-manifests/apps/admission-webhook/upstream/overlays/cert-manager
# Notebook Controller
- kubeflow-manifests/apps/jupyter/jupyter-web-app/upstream/overlays/istio
# Jupyter Web App
- kubeflow-manifests/apps/jupyter/notebook-controller/upstream/overlays/kubeflow
# Profiles + KFAM
- kubeflow-manifests/apps/profiles/upstream/overlays/kubeflow
# Volumes Web App
- kubeflow-manifests/apps/volumes-web-app/upstream/overlays/istio
# Tensorboards Web App
-  kubeflow-manifests/apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# Tensorboard Controller
-  kubeflow-manifests/apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
# Training Operator
- kubeflow-manifests/apps/training-operator/upstream/overlays/kubeflow
# MPI Operator
- kubeflow-manifests/apps/mpi-job/upstream/overlays/kubeflow
# User namespace
- kubeflow-manifests/common/user-namespace/base

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Service
  metadata:
    name: istio-ingressgateway
    namespace: istio-system
  spec:
    type: LoadBalancer

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: kubeflow
secretGenerator:
  - name: public-cert
    namespace: istio-system
    type: "kubernetes.io/tls"
    files:
      - "tls.key=kubeflow.vivplatform.io-key.pem"
      - "tls.crt=kubeflow.vivplatform.io.pem"