apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: batcave

resources:
  - ../../base
  - batcave-landing-zone.yaml

configurations:
  - kustomizeconfig.yaml

patchesStrategicMerge:
  - reclaimpolicy-patch.yaml
  - patch-batcave.yaml

configMapGenerator:
  - name: argocd-values
    files:
      - values.yaml=configs/argocd-values.yaml
  - name: authmanager-values
    files:
      - values.yaml=configs/authmanager-values.yaml
  - name: fluentbit-values
    files:
      - values.yaml=configs/fluentbit-values.yaml
  - name: gitlab-runner-values
    files:
      - values.yaml=configs/gitlab-runner-values.yaml
  - name: gitlab-values
    files:
      - values.yaml=configs/gitlab-values.yaml
  - name: jaeger-values
    files:
      - values.yaml=configs/jaeger-values.yaml
  - name: kiali-values
    files:
      - values.yaml=configs/kiali-values.yaml
  - name: kyverno-values
    files:
      - values.yaml=configs/kyverno-values.yaml
  - name: loki-values
    files:
      - values.yaml=configs/loki-values.yaml
  - name: monitoring-values
    files:
      - values.yaml=configs/monitoring-values.yaml
  - name: pod-limits-values
    files:
      - values.yaml=configs/pod-limits-values.yaml
  - name: sso-values
    files:
      - values.yaml=configs/sso-values.yaml
  - name: toleration-values
    files:
      - values.yaml=configs/toleration-values.yaml
  - name: velero-values
    files:
      - values.yaml=configs/velero-values.yaml
