apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: batcave
stringData:
    values.yaml: ENC[AES256_GCM,data:7ax4hGwAsucX50BxaQk2Trulf+HgTxTQstpg1IcK+61toFpCqK/02zNMQN5OXDtvUcVqkysRDdh2js0VPgI1n4q27xzQK9nAfQs=,iv:/SGjvoGoVi8v4N/DF3yBCUSabjT6DNyh+Bb+PASxgjk=,tag:F3VGe+bhns7hczPIdht5GQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:863306670509:key/a0c98664-e12a-44b1-b3b0-4bb062de7a9e
          created_at: "2022-08-09T13:51:49Z"
          enc: AQICAHjVziYnlSHY7Z0eQ3Zqgn8agwi4T/rSvC3849mciM/AHgE0nAJfZpGenUnYc/wnJNsWAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMalTJpUecMCrKJePkAgEQgDuhFMr6qK/7EZOPd9JVg6ZV4u1GHqpZYQVZqMV4uBa6lGHHYNjKizftQE9gjtW1l7DaYb4sps9mVk0xJQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-09T13:51:49Z"
    mac: ENC[AES256_GCM,data:wC49JMEo030znQJVadTcHcuk1fE9oo4ShGYnoifFlLuaW1rsXBRysdaYEygH0YQIpkChj2L+1QnIIFtQScgNlTPMWFTYrcGBc/rkm5u/wJJyji7m3e0gBQV4UgzQdVFbe2UvAfdqoPbqMgUoirdg9LV1JKqKWlXTdo9hdhVyuG8=,iv:hXL+3cBPk3vIQdQT6rkGiUMXNe5l/F701MvGW3DWlPY=,tag:T5kj3jOU9WXSebzUiJLzhA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
