# Create the CustomerResourceDefinition for MongoDB custom types.
createCrds: true

# Name of the Namespace to use
namespace: mongodb-operator

# Set this to true if your cluster is managing SecurityContext for you.
# If running OpenShift (Cloud, Minishift, etc.), set this to true.
managedSecurityContext: false

operator:
  # Execution environment for the operator, dev or prod. Use dev for more verbose logging
  env: prod

  # Name that will be assigned to most of internal Kubernetes objects like Deployment, ServiceAccount, Role etc.
  name: mongodb-enterprise-operator

  # Name of the deployment of the operator pod
  deployment_name: mongodb-enterprise-operator

  # Version of mongodb-enterprise-operator and mongodb-enterprise-database images
  version: 1.5.3

  # The Custom Resources that will be watched by the Operator. Needs to be changed if only some of the CRDs are installed
  watchedResources:
  - mongodb
  - opsmanagers
  - mongodbusers

database:
  name: mongodb-enterprise-database

opsManager:
  name: mongodb-enterprise-ops-manager
  version: 4.4.14

initOpsManager:
  name: mongodb-ops-manager-init
  version: 1.0.0

appDb:
  name: mongodb-ops-manager-appdb
  version: 1.5.3

initAppDb:
  name: mongodb-ops-manager-appdb-init
  version: 1.5.3

registry:
  imagePullSecrets:
  # TODO: specify for each image and move there?
  pullPolicy: Always
  # Specify if images are pulled from private registry
  operator: registry1.dso.mil/ironbank/mongodb/mongodb-enterprise
  initOpsManager: registry1.dso.mil/ironbank/mongodb/mongodb-enterprise
  opsManager: registry1.dso.mil/ironbank/mongodb/mongodb-enterprise
  initAppDb: registry1.dso.mil/ironbank/mongodb/mongodb-enterprise
  appDb: registry1.dso.mil/ironbank/mongodb/mongodb-enterprise

# Set this to true if the operator will require Kubernetes CA
# infrastructure to generate TLS certificates.
needsCAInfrastructure: true

# Set this to false to disable subresource utilization
# It might be required on some versions of Openshift
subresourceEnabled: true
