apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: rapidfort
  namespace: batcave
spec:
  interval: 1m0s
  url: https://repo1.dso.mil/platform-one/big-bang/apps/third-party/rapidfort.git
  ref:
    tag: 1.1.16-bb.0
  