apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: batcave

resources:
  - ../../base
  - batcave-landing-zone.yaml

configurations:
  - kustomizeconfig.yaml

patchesStrategicMerge:
  - reclaimpolicy-patch.yaml
  - patch-batcave.yaml

configMapGenerator:
  - name: gitlab-runner-values
    files:
      - values.yaml=configs/gitlab-runner-values.yaml
  - name: gitlab-values
    files:
      - values.yaml=configs/gitlab-values.yaml
  - name: monitoring-values
    files:
      - values.yaml=configs/monitoring-values.yaml
  - name: sso-values
    files:
      - values.yaml=configs/sso-values.yaml
  - name: velero-values
    files:
      - values.yaml=configs/velero-values.yaml
