apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: falco
  namespace: batcave
spec:
  interval: 1m0s
  path: "./apps/falco"
  sourceRef:
    kind: GitRepository
    name: batcave-landing-zone
    namespace: batcave
  prune: true