apiVersion: v1
kind: Secret
metadata:
    name: gitlab-secret
    namespace: batcave
stringData:
    values.yaml: ENC[AES256_GCM,data:hgM3pfUtoIGhsovwpu2rcJ+42B13YLbW2McXzdxWO2zS5RJyNeAuh1CCNIXZQKYBp5V+hmegSIT8aTCdWiJUohO/C23SvXcUKn4RYBoUXZIh7SGGjg==,iv:PshaVlf5yG/VI/utexYHqZLjM8N3uHFrMnRdUGZg7OY=,tag:iYat7j29jWn69t/3s8ZRSg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:863306670509:key/a0c98664-e12a-44b1-b3b0-4bb062de7a9e
          created_at: "2022-03-18T18:24:22Z"
          enc: AQICAHjVziYnlSHY7Z0eQ3Zqgn8agwi4T/rSvC3849mciM/AHgFrxXC2j6YuDYeDdpR83lplAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMXCrMoAING+RjL5v0AgEQgDvXonDtrzDcomH28uRCpnTfPoltHbwnZosERv3wTHPAgzwvzEHXUMZDFqkUV1tli5sjdiI/xeOocmqYug==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-18T18:24:22Z"
    mac: ENC[AES256_GCM,data:ceVBazukvuItK4PAv1EWQxjAAcFC3lEg84K3Cph/n4dOroiLiIox4OGzhykWYIq7Uk3mC8Terg4fz1/3WZQaeVPVNcc/CZi53HmZiobyq68jDUJNeSa1Rae3RpiOb4JfYLGxlZsKnGV1GBBFvLgCfLZTLpKJ6ZzkMatfGDo5s1Y=,iv:CHuCQuwXXoyQrGZ+lOlUkscaZqqwsOBXX5/+EuuICfw=,tag:UFXW8M/frIGhzWeO6cTzEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
