apiVersion: v1
kind: Secret
metadata:
    name: kiali
    namespace: kiali
type: kubernetes.io/opaque
stringData:
    oidc-secret: ENC[AES256_GCM,data:2oZf04d9gA8fkl/Vrb84Ivr5czvtmLvn9wrnCup7XQ5PCKNFO9TkDQ==,iv:aHry9hNkNt1n2Z49aHO+LqUPC8qpyupJTtfMU7o7P/E=,tag:8bRlHzYn13W7fCWLI3VVIg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:863306670509:key/a0c98664-e12a-44b1-b3b0-4bb062de7a9e
          created_at: "2022-04-12T15:11:14Z"
          enc: AQICAHjVziYnlSHY7Z0eQ3Zqgn8agwi4T/rSvC3849mciM/AHgG0r/2vnoinZjNO3s7l0VBDAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMGNruXUWY6UNvPyClAgEQgDuXb690QmkvyjmDI1sX1hJGEpIXBv1AhXx5Q5GJ0Juqy+2iVUCVx61MTIX3DtIGWqmK2zFVygJnFmlj6g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-12T15:11:15Z"
    mac: ENC[AES256_GCM,data:NXWrGD1D9YKqIr/f4pgz9UGXzFDzKhcHZLPRguNLFm0Y1+5tS9A4/bxC9YEcakJJG9GdvxniUfsSu+lXn7e/l/jgErApnrsrWoqVz208BUIbEQG6QegodOnjNUXNQ9oDc81rmvWwG+DFPkaj8mMDN/+RkdgQkhORVttFVy2zG90=,iv:vK1+Uy7vpb/Ed8xnVstymdymE11VTtqIO5Hjv6r2ZV4=,tag:uArJZ+exS3BaPDCPVgqxsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
