---

- name: "5.1 | PATCH | Ensure 'Print Spooler (Spooler)' is set to 'Disabled' (DC only)"
  win_regedit:
      path: HKLM:\System\CurrentControlSet\Services\Spooler
      name: Start
      data: 0
      type: dword
  when:
      - rule_5_1
      - ansible_windows_domain_role == "Primary domain controller"
  tags:
      - level1-domaincontroller
      - rule_5.1
      - patch

- name: "5.2 | PATCH | Ensure 'Print Spooler (Spooler)' is set to 'Disabled' ( MS only)"
  win_regedit:
      path: HKLM:\System\CurrentControlSet\Services\Spooler
      name: Start
      data: 0
      type: dword
  when:
      - rule_5_2
      - not ansible_windows_domain_role == "Primary domain controller"
  tags:
      - level1-memberserver
      - rule_5.2
      - patch
