apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: batcave

commonLabels:
  owner: batcave

resources:
  - rapidfort-gitrepository.yaml
  - rapidfort-helmrelease.yaml

configMapGenerator:
  - name: rapidfort-base-values
    files:
      - values.yaml=rapidfort-base-values.yaml