---
- name: Find $CATALINA_HOME directory
  shell: cat /etc/systemd/system/tomcat.service | grep "CATALINA_HOME" | cut -f3 -d= | tr -d '"'
  changed_when: false
  register: catalina_find_home_dir

- name: Install needed packages
  block:
      - name: Install RHEL7 based packages
        yum:
            name: ['python-lxml', 'auditd']
            state: present
        when:
            - ansible_distribution == "RedHat"
            - ansible_distribution_major_version == "7"

      - name: Install CentOS7 based packages
        yum:
            name: ['python-lxml', 'audit']
            state: present
        when:
            - ansible_distribution == "CentOS"
            - ansible_distribution_major_version == "7"

      - name: Install RHEL8 based packages
        dnf:
            name: ['python3-lxml', 'audit']
            state: present
        when:
            - ansible_distribution_file_variety == "RedHat"
            - ansible_distribution_major_version == "8"

      - name: Install Ubuntu based packages
        apt:
            name: ['python3-lxml', 'auditd']
            state: present
        when: ansible_distribution_file_variety == "Debian" and ansible_distribution_major_version == "16" or ansible_distribution_major_version == "18" or ansible_distribution_major_version == "20"


# - name: Install RHEL 7 Tomcat 9
#   yum:
#       name: tomcat
#       state: present
#   when: 
#       - tcat_install
#       - ansible_distribution_file_variety == "RedHat"
#       - ansible_distribution_major_version == "7" or
#         ansible_distribution_major_version == "8"

# - name: Install Ubuntu 18 and 20 Tomcat 9
#   block:
#       - name: Prep for Tomcat | Update apt
#         apt:
#             update_cache: yes

#       - name: Prep For Tomcat | Upgrade software
#         apt:
#             name: "*"
#             state: latest

#       - name: Install Ubuntu Tomcat 9
#         apt:
#             name: tomcat9
#             state: present
#   when: 
#       - tcat_install
#       - ansible_distribution_file_variety == "Debian"
#       - ansible_distribution_major_version == "18" or 
#         ansible_distribution_major_version == "20"

- name: Install Tomcat
  include_tasks: install_tomcat.yml
  when:
    - tcat_install