apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: k3d-values
  namespace: batcave
spec:
  interval: 1m0s
  path: "./apps/batcave/envs/k3d/"
  sourceRef:
    kind: GitRepository
    name: batcave-landing-zone
    namespace: batcave
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: terragrunt-vars
