apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: bigbang
  namespace: batcave
spec:
  interval: 1m0s
  url: https://repo1.dso.mil/platform-one/big-bang/bigbang.git
  ref:
    tag: 1.41.0
