{{- if and .Values.networkPolicies.enabled .Values.monitoring.enabled}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-metric-scraping
  namespace: "{{ .Release.Namespace }}"
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
                app.kubernetes.io/name: monitoring
          podSelector:
            matchLabels:
              app: prometheus
      ports:
        - port: 8888
          protocol: TCP
  podSelector:
    matchLabels:
      app: '{{ template "gatekeeper.name" . }}'
  policyTypes:
    - Ingress
{{- end }}
