{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-webhooks-from-api
  namespace: "{{ .Release.Namespace }}"
spec:
  ingress:
    - from:
      - ipBlock:
          cidr: 0.0.0.0/0
      ports:
        - port: 8443
          protocol: TCP
  podSelector:
    matchLabels:
      app: '{{ template "gatekeeper.name" . }}'
      chart: '{{ template "gatekeeper.name" . }}'
      control-plane: controller-manager
      gatekeeper.sh/operation: webhook
      gatekeeper.sh/system: "yes"
      heritage: '{{ .Release.Service }}'
      release: '{{ .Release.Name }}'
  policyTypes:
    - Ingress
{{- end }}
