apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: batcave-landing-zone
  namespace: batcave
spec:
  interval: 1m0s
  url: ssh://git@github.com/CMSgov/batcave-landing-zone.git
  ref:
    tag: 0.22.0
  secretRef:
    name: gh-credentials
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: values
  namespace: batcave
spec:
  interval: 1m0s
  path: "./apps/batcave/envs/prod/"
  sourceRef:
    kind: GitRepository
    name: batcave-landing-zone
    namespace: batcave
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: terragrunt-vars
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: batcave-ns-secrets
  namespace: batcave
spec:
  interval: 1m0s
  path: "./apps/batcave/envs/prod/secrets/batcave-ns"
  sourceRef:
    kind: GitRepository
    name: batcave-landing-zone
    namespace: batcave
  prune: true
  decryption:
    provider: sops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-ns-secrets
  namespace: batcave
spec:
  interval: 1m0s
  path: "./apps/batcave/envs/prod/secrets/app-ns"
  sourceRef:
    kind: GitRepository
    name: batcave-landing-zone
    namespace: batcave
  prune: true
  dependsOn:
    - name: batcave-ns-secrets
  decryption:
    provider: sops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: defectdojo
  namespace: batcave
spec:
  interval: 1m0s
  path: "./apps/defectdojo"
  sourceRef:
    kind: GitRepository
    name: batcave-landing-zone
    namespace: batcave
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: terragrunt-vars
---
# Cannot be moved to base because we want remote overlays to be
# able to create their own Batcave HR + overlay
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: batcave
  namespace: batcave
spec:
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: bigbang
        namespace: batcave
  interval: 2m0s
  rollback:
    disableWait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cosign
  namespace: batcave
spec:
  interval: 1m0s
  path: "./apps/cosign"
  sourceRef:
    kind: GitRepository
    name: batcave-landing-zone
    namespace: batcave
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: terragrunt-vars
