client:
  ignore-redirect: true
  timeout: 5s
endpoints:
  - name: ArgoCD
    group: batcave-impl Utility Belt
    url: https://argocd.batcave-impl.internal.cms.gov?healthcheck=gatus.batcave-impl.internal.cms.gov
    interval: 5m
    client:
      ignore-redirect: true
      timeout: 5s
    conditions:
      - '[STATUS] < 400'
      - '[RESPONSE_TIME] < 2s'
      - '[CERTIFICATE_EXPIRATION] > 1d'
      - '[CERTIFICATE_EXPIRATION] > 30d'
  - name: Kiali
    group: batcave-impl Utility Belt
    url: https://kiali.batcave-impl.internal.cms.gov?healthcheck=gatus.batcave-impl.internal.cms.gov
    interval: 5m
    client:
      ignore-redirect: true
      timeout: 5s
    conditions:
      - '[STATUS] < 400'
      - '[RESPONSE_TIME] < 2s'
      - '[CERTIFICATE_EXPIRATION] > 1d'
      - '[CERTIFICATE_EXPIRATION] > 30d'
  - name: Grafana
    group: batcave-impl Utility Belt
    url: https://grafana.batcave-impl.internal.cms.gov?healthcheck=gatus.batcave-impl.internal.cms.gov
    interval: 5m
    client:
      ignore-redirect: true
      timeout: 5s
    conditions:
      - '[STATUS] < 400'
      - '[RESPONSE_TIME] < 2s'
      - '[CERTIFICATE_EXPIRATION] > 1d'
      - '[CERTIFICATE_EXPIRATION] > 30d'
  - name: Alert Manager
    group: batcave-impl Utility Belt
    url: https://alertmanager.batcave-impl.internal.cms.gov?healthcheck=gatus.batcave-impl.internal.cms.gov
    interval: 5m
    client:
      ignore-redirect: true
      timeout: 5s
    conditions:
      - '[STATUS] < 400'
      - '[RESPONSE_TIME] < 2s'
      - '[CERTIFICATE_EXPIRATION] > 1d'
      - '[CERTIFICATE_EXPIRATION] > 30d'
  - name: Jaeger
    group: batcave-impl Utility Belt
    url: https://tracing.batcave-impl.internal.cms.gov?healthcheck=gatus.batcave-impl.internal.cms.gov
    interval: 5m
    client:
      ignore-redirect: true
      timeout: 5s
    conditions:
      - '[STATUS] < 400'
      - '[RESPONSE_TIME] < 2s'
      - '[CERTIFICATE_EXPIRATION] > 1d'
      - '[CERTIFICATE_EXPIRATION] > 30d'
  - name: EASi
    group: ADO Apps
    url: https://easi.batcave-impl.internal.cms.gov/?healthcheck=gatus.batcave-impl.internal.cms.gov
    interval: 5m
    client:
      ignore-redirect: true
      timeout: 5s
    conditions:
      - '[STATUS] < 400'
      - '[RESPONSE_TIME] < 2s'
      - '[CERTIFICATE_EXPIRATION] > 1d'
      - '[CERTIFICATE_EXPIRATION] > 30d'
  - name: EPPE
    group: ADO Apps
    url: https://eppe-drupal.batcave-impl.internal.cms.gov/?healthcheck=gatus.batcave-impl.internal.cms.gov
    interval: 5m
    client:
      ignore-redirect: true
      timeout: 5s
    conditions:
      - '[STATUS] < 400'
      - '[RESPONSE_TIME] < 2s'
      - '[CERTIFICATE_EXPIRATION] > 1d'
      - '[CERTIFICATE_EXPIRATION] > 30d'
  - name: KnightLight
    group: ADO Apps
    url: https://knight-light.batcave-impl.internal.cms.gov/?healthcheck=gatus.batcave-impl.internal.cms.gov
    interval: 5m
    client:
      ignore-redirect: true
      timeout: 5s
    conditions:
      - '[STATUS] < 400'
      - '[RESPONSE_TIME] < 2s'
      - '[CERTIFICATE_EXPIRATION] > 1d'
      - '[CERTIFICATE_EXPIRATION] > 30d'
  - name: batCAVE GitLab
    group: External Dependencies
    url: https://code.batcave.internal.cms.gov/explore?healthcheck=gatus.batcave-impl.internal.cms.gov
    interval: 5m
    client:
      ignore-redirect: true
      timeout: 5s
    conditions:
      - '[STATUS] < 400'
      - '[RESPONSE_TIME] < 2s'
      - '[CERTIFICATE_EXPIRATION] > 1d'
      - '[CERTIFICATE_EXPIRATION] > 30d'
  - name: CMS Artifactory
    group: External Dependencies
    url: https://artifactory.cloud.cms.gov/?healthcheck=gatus.batcave-impl.internal.cms.gov
    interval: 5m
    client:
      ignore-redirect: true
      timeout: 5s
    conditions:
      - '[STATUS] < 400'
      - '[RESPONSE_TIME] < 2s'
      - '[CERTIFICATE_EXPIRATION] > 1d'
      - '[CERTIFICATE_EXPIRATION] > 30d'
  - name: GitHub
    group: External Dependencies
    url: https://www.github.com/?healthcheck=gatus.batcave-impl.internal.cms.gov
    interval: 5m
    client:
      ignore-redirect: true
      timeout: 5s
    conditions:
      - '[STATUS] < 400'
      - '[RESPONSE_TIME] < 2s'
      - '[CERTIFICATE_EXPIRATION] > 1d'
      - '[CERTIFICATE_EXPIRATION] > 30d'
