apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${batcave_cluster_name}-cosign
  namespace: gitlab
  annotations:
    eks.amazonaws.com/audience: sigstore
    eks.amazonaws.com/role-arn: ${cosign_iam_role_arn}
