---
- name: List all repositories
  find: paths=/etc/yum.repos.d/ patterns=*.repo
  register: current_repos

- name: Remove all repositories
  file: path={{item.path}} state=absent
  with_items: '{{current_repos.files}}'

- name: Add installation repository
  yum_repository: name=packer description=packer enabled=no gpgcheck=no baseurl='{{packer_os.repo_server}}/{{ansible_distribution_version}}/os/$basearch'
