apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs
reclaimPolicy: Delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-immediate
reclaimPolicy: Delete
