apiVersion: v1
kind: Secret
metadata:
    name: registry-credentials
    namespace: batcave
stringData:
    values.yaml: ENC[AES256_GCM,data:StGwpHY98m5eSR51Dz0gQfMmPNTHAD43q/GHKllbIWJtG0X5+pZhm8YD5Cb0nFoRwRKlWUmG4sly0FGGEnRBAxS29gvlHP/Zz4qat9IxdxscCZ7i5fJnSHl7A62yOI5glUgCzGGqX+G5ZEQnMXP6M5Yxh+oZX7j34oXy7WvSurrD4pBEq9BAIsZGwKBBLoga3vD8CQipUs/Ptoare6latw6MRej7vwiZevOQFInYd2mH+7m70oc+nzXTrZfbDGYdXRfFvWwXjfX79mONQlYhaHADtXiP9HCbKwp1iWxzdkgZwXnnZ0H5O4q6KX5RKd0hSV7moVOzU4We9/j25VjzNPnhCnAD0wk0vTxkn3mgCW+QYZw16w2WdIW5I7qg7ng81bi2QtwxTkeXIp7mPTdOUxbBqkNXacaC73aea0cj7qU2,iv:DBwY8n4G8qKviO95MgYuP9Ca4pnqFXJ4lkG9CXgph8s=,tag:PgonMKN6Dd4wWXOGvkX4Bw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:111594127594:key/cbfacbe4-73d6-45a3-8d81-71aaf1d2da46
          created_at: "2022-06-13T20:43:23Z"
          enc: AQICAHgiU+VfwEi1Pxgq+/+C0hPpMTfUqUrVLp8B37oeutKJmgHAThb1XikAuzk1oM84nVhZAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMwIIYzIKZOzYuHskRAgEQgDs03/lUtlO8rPwo/Di6bIwbMRacTOkMNUNskexrvdukZXy1aYlWu8yZjvpDYAmeZN03QKIlPFFK+kV5gg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-06-13T20:43:23Z"
    mac: ENC[AES256_GCM,data:pucFFZ0d/wl/KoELW+NaK8pIfmaE17EewvZ09x+JRMFdLaHq/Sk/UbSmkMCbQK7HoAgAjSEN9GYdchSD6yG5rpr53hjzvM8xijDinpGg1j1dP4LAvXz7K/CLUvD1zxN2EHvZl8++tPxRRtbPIO0dca00vJNw2lvsgvEB2CE0VG4=,iv:qTscdteovsKlNwyfhZd1B4vlhY92TiWupZKWkeaz91c=,tag:KYL9rOW1Jwm7UpqKVVn7dA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
