---

- name: "SETUP | SECTION 4 | Setup Tasks"
  block:
  - name: "SETUP | SECTION 4 | Evidence Message"
    set_fact:
      exception_evidence_message: "No SQL Servers Exist"

  - name: "SETUP | SECTION 4 | Get SQL Server List"
    command: "az sql server list"
    register: azure_sql_server_list_raw
    changed_when: false

  - name: "SETUP | SECTION 4 | Format SQL Server List"
    set_fact:
      azure_sql_server_list: "{{ azure_sql_server_list_raw.stdout | from_json | default([],true) }}"

  - name: "SETUP | SECTION 4 | Get SQL Database List"
    command: "az sql db list --server {{ item.name }} --resource-group {{ item.resourceGroup }}"
    loop: "{{ azure_sql_server_list }}"
    register: azure_sql_db_list_raw
    changed_when: false

  - name: "SETUP | SECTION 4 | Format SQL Database List"
    set_fact:
      azure_sql_db_list: '{{ azure_sql_db_list_raw | json_query("results[*].stdout") | map("from_json") | list | json_query("[].id") | default([],true) }}'

  - name: "SETUP | SECTION 4 | Get SQL Server Audit Policy Show"
    command: "az sql server audit-policy show --name {{ item.name }} --resource-group {{ item.resourceGroup }}"
    loop: "{{ azure_sql_server_list }}"
    register: azure_sql_server_audit_policy_show_raw
    changed_when: false

  - name: "SETUP | SECTION 4 | Format SQL Server Audit Policy Show"
    set_fact:
      azure_sql_server_audit_policy_show: '{{ azure_sql_server_audit_policy_show_raw | json_query("results[*].stdout") | map("from_json") | list | default([],true) }}'

  when:
    - azfcis_section4
    - azfcis_rule_4_1_1 or
      azfcis_rule_4_1_2 or
      azfcis_rule_4_1_3 or
      azfcis_rule_4_2_1 or
      azfcis_rule_4_2_2 or
      azfcis_rule_4_2_3 or
      azfcis_rule_4_2_4 or
      azfcis_rule_4_2_5 or
      azfcis_rule_4_2_6 or
      azfcis_rule_4_2_7 or
      azfcis_rule_4_2_8 or
      azfcis_rule_4_4 or
      azfcis_rule_4_5
  tags:
    - section4
    - rule_4.1.1
    - rule_4.1.2
    - rule_4.1.3
    - rule_4.2.1
    - rule_4.2.2
    - rule_4.2.3
    - rule_4.2.4
    - rule_4.2.5
    - rule_4.2.6
    - rule_4.2.7
    - rule_4.2.8
    - rule_4.4
    - rule_4.5

