---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    benchmark:
      name: "{{ 'CIS Microsoft Azure Foundations Benchmark' | replace(' ','_') }}"
      version: 1.2.0
      profile: "{{ }}"
  become: true
  collections:
    - azure.azcollection
    - ansible.posix
  roles:
    - role: "{{ playbook_dir }}"
      system_is_container: "{{ is_container | default(false) }}"

